### ISSUE TITLE
Very small image does not get centered properly but the face is detected correctly

### ISSUE THREAD

**Issue by Dean151** [BeauNouvelle/FaceAware#10]
Here is an example of an image that do not work
![simulator screen shot 10 oct 2016 a 13 13 22](https://cloud.githubusercontent.com/assets/8696821/19234381/8d7c3068-8eeb-11e6-8cf9-781421fc9237.png)

**Comment by Dean151** [comment]
It seems that's it's more likely that the face detected and the image size make the calculation go wrong

**Comment by Dean151** [comment]
![picture-1591-1443019236](https://cloud.githubusercontent.com/assets/8696821/19237546/c8f43eee-8efd-11e6-9f50-250ba973ec3e.jpg)
Feel free to try

**Comment by BeauNouvelle** [comment]
Thanks, will look into this.

**Comment by algrid** [comment]
Hi! I added a PR that fixes this problem.

**Comment by BeauNouvelle** [comment]
@algrid Thanks for taking the time to fix this! Will update pods soon.
