### ISSUE TITLE
Getting a strange "Blinking"

### ISSUE THREAD

**Issue by oferRounds** [BeauNouvelle/FaceAware#18]
Hi @BeauNouvelle 

Any idea why would I see the following issue: when `focusOnFaces` is set On I get a strange issue where the image is being seen for a brief moment, then it disappears and the re-apears. It all happens very fast but the issue is noticeable and happens every time.

Any thoughts maybe?

**Comment by BeauNouvelle** [comment]
Not too sure on this, but I can investigate. Perhaps the image gets drawn before the readjustment is made, and redrawn? Sounds like a bug!

**Comment by oferRounds** [comment]
Thank you! Let me know if you need any info from me.

**Comment by oferRounds** [comment]
And your idea of what happens sounds reasonable to me

**Comment by oferRounds** [comment]
@BeauNouvelle - just to add more info: I use FaceAware with PinRemoteImage. Specifically, with their `UIImageView`’s Category: `PINImageView+PINRemoteImage`. I use its method to `pin_setImageFromURL:completion`, and then on its completion block, I set `focusOnFaces` to true.

**Comment by timroesner** [comment]
I have the same issue with SD_WebImage in the completion block where images briefly "flash". For me the image is set with out focus on face first and then readjusted. It would be nice to maybe add a fade in animation to make this change less noticeable.

**Comment by BeauNouvelle** [comment]
I'll have a play around with it this weekend and see if I can come up with a solution.
If only the face recognition was faster.

**Comment by Eldhose-Islet** [comment]
I also have the issue. 
The reason for this is there is a placeholder image, which may not need to be face focused. The image cashing library first sets image as placeholder image. The library tries to detect face async, which will take time, and loads image.Then the image cashing library loads with original image.. Is there any way to avoid face detection of placeholder image?

**Comment by richard1991** [comment]
Hi, it seems that this problem still exists, is there a plan to fix it?

**Comment by Ve4noMolodoy** [comment]
> I have the same issue with SD_WebImage in the completion block where images briefly "flash". For me the image is set with out focus on face first and then readjusted. It would be nice to maybe add a fade in animation to make this change less noticeable.

This problem occurs because of the use self.image = nil in focusOnFaces. You can comment out this. Same problem with SDWebImage

**Comment by BeauNouvelle** [comment]
I've removed that line of code in version 2.0.1

Sorry this has taken so long.
