### ISSUE TITLE
Xcode 9: UIImageView.image must be used from main thread only

### ISSUE THREAD

**Issue by timroesner** [BeauNouvelle/FaceAware#22]
As the title says Xcode 9 gives me a nice title purple exclamation mark telling me that FaceAware is using a method where UIImageView.image is not run on the main thread.

**Comment by timroesner** [comment]
This is the exact error I get now after updating to your newest commit:

UIView.bounds must be used from main thread only

This happens at line 95

**Comment by BeauNouvelle** [comment]
I'll get a fix out today for this.

In future, if you're comfortable enough, fork it, make some adjustments and send through a pull request. I'd be happy to review and merge in your changes!

**Comment by timroesner** [comment]
Yeah I tried some fixes but wasn’t able to get thanks for looking into it though

**Comment by BeauNouvelle** [comment]
@timroesner should be good to go!
