### ISSUE TITLE
How can I know the image FaceAware finished ?

### ISSUE THREAD

**Issue by CocoaML** [BeauNouvelle/FaceAware#26]
How can I know the image FaceAware finished ? Use Block ?

**Comment by CocoaML** [comment]
Would you like to help me ? @diejmon @T-Pham @jk2K @algrid @omaralbeik

**Comment by omaralbeik** [comment]
@CocoaML Will try to take a look this weekend

**Comment by CocoaML** [comment]
> @CocoaML Will try to take a look this weekend

Thanks For your quick reply
