### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by CocoaML** [BeauNouvelle/FaceAware#32]
`                WeakSelf(imageView)
                [imageView sd_setImageWithURL:[NSURL URLWithString:url] completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
              weakimageView.image = image;
              weakimageView.focusOnFaces = YES;
                }];
`

When I scroll the TableView, This code will be performed.( I used `SDWebImage` to set ImageView image and Then focusOnFaces )  
And the memory report The memory used so high.

What can do to reduce memory ?

**Comment by CocoaML** [comment]
The code is Here :

`WeakSelf(imageView)`
`[imageView sd_setImageWithURL:[NSURL URLWithString:url] completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {`
` weakimageView.image = image; `
`weakimageView.focusOnFaces = YES;`
`}];`

**Comment by CocoaML** [comment]
@diejmon @T-Pham @jk2K @algrid 
About The FaceAware memory issue, I did a Project, link is https://github.com/CocoaML/SDWebImageAndFaceAwareDemo , 
The memory report memory uses so high.

What can do to reduce memory ?

**Comment by BeauNouvelle** [comment]
Thank you. I'll try and take a look at this over the weekend.

**Comment by CocoaML** [comment]
`   

            let layer = self.imageLayer()

           layer.contents = newImage.cgImage

            layer.frame = CGRect(x: offset.x, y: offset.y, width: finalSize.width, height: finalSize.height)
       `

This Code is make memory uses so high ?  Or what ?  Can you give me some advice ? Thank you.

**Comment by diejmon** [comment]
@CocoaML You load all the images in memory with original size. Instead what you shall do is downscale images which are used in table view cells and use them instead. This will take a way less memory.

**Comment by CocoaML** [comment]
> @CocoaML You load all the images in memory with original size. Instead what you shall do is downscale images which are used in table view cells and use them instead. This will take a way less memory.

Fine, Thanks For you quick reply.
