### ISSUE TITLE
Doesn't handle frame changes

### ISSUE THREAD

**Issue by DavidPhillipOster** [BeauNouvelle/FaceAware#7]
If the frame changes aspect ratio, the visible image layer isn't recomputed with the new aspect ratio.

This is easiest to see on with a full-screen view that handles rotation on a  long thin device like an iPhone 5, when you rotate from portrait to landscape the preserved pixels from the original image should be different between the two modes.

**Comment by glennposadas** [comment]
Is this solved, good @BeauNouvelle ? :) Thanks!

**Comment by BeauNouvelle** [comment]
@glennposadas Not yet. I started on it but wasn't really sure how to approach listening to the screen rotation event. Difficult with an extension. Haven't had much time to revisit.
