### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by jyounus** [BeauNouvelle/FaceAware#9]
Hey there,

First of all, thanks for making this open source! I wanted to ask if you're planning to make this available via Cocoapods? 

Thanks

**Comment by BeauNouvelle** [comment]
Looking into it! 
Haven't added cocoapods support to a project like this before.

Have a [frame change](https://github.com/BeauNouvelle/AspectFillFaceAware/issues/7) issue to work through before then though.

Thanks for the feedback!

**Comment by BeauNouvelle** [comment]
Done!
